### Listar productos
GET http://127.0.0.1:3000/producto

###guardar 

POST http://127.0.0.1:3000/producto
Content-Type: application/json

{ "nombre": "Procesador", "cantidad": 25, "precio": 500 }

###Mostrar producto
GET http://127.0.0.1:3000/producto/80

###Modificar producto
PUT http://127.0.0.1:3000/producto/20 
Content-Type: application/json

{"nombre":"gabu2",
"precio":1
}

###Borrar
DELETE http://127.0.0.1:3000/producto/gabu3


###
PUT http://127.0.0.1:3000/producto/gabu3
Content-Type: application/json

{
    "nombre":"monitor gamer",
    "precio":300
}